In [1]:
import pandas as pd

In [2]:
train = pd.read_csv('dataset/train.csv')
train.head()

,candidate_id,query_id,snapshot_date,seller_id,region,primary_category,seller_tier,week_of_year,month,quarter,...,visibility_boost,inventory_synergy,loyalty_synergy,margin_penalty,cross_border_fit,new_seller_fit,seasonal_fit,cost_tier,is_relevant,tool_recently_used
0,cand_00000000,qry_0000000,2024-01-08,sel_00000,west,apparel,growth,2,1,1,...,0.10,0.40,0.10,0.35,-0.05,0.10,0.20,low,0,0
1,cand_00000001,qry_0000000,2024-01-08,sel_00000,west,apparel,growth,2,1,1,...,0.14,0.18,0.10,0.20,-0.20,0.08,0.12,medium,0,0
2,cand_00000002,qry_0000000,2024-01-08,sel_00000,west,apparel,growth,2,1,1,...,0.12,0.12,0.18,0.45,0.04,0.02,0.16,high,0,0
3,cand_00000003,qry_0000000,2024-01-08,sel_00000,west,apparel,growth,2,1,1,...,0.16,0.34,0.12,0.16,0.05,0.04,0.10,medium,0,0
4,cand_00000004,qry_0000000,2024-01-08,sel_00000,west,apparel,growth,2,1,1,...,0.24,0.42,0.02,0.40,-0.08,0.06,0.36,medium,1,1

In [7]:
test = pd.read_csv('dataset/test.csv')
test.head()

,candidate_id,query_id,snapshot_date,seller_id,region,primary_category,seller_tier,week_of_year,month,quarter,...,discount_depth,visibility_boost,inventory_synergy,loyalty_synergy,margin_penalty,cross_border_fit,new_seller_fit,seasonal_fit,cost_tier,tool_recently_used
0,cand_00211200,qry_0026400,2024-06-10,sel_00000,west,apparel,growth,24,6,2,...,0.18,0.10,0.40,0.10,0.35,-0.05,0.10,0.20,low,0
1,cand_00211201,qry_0026400,2024-06-10,sel_00000,west,apparel,growth,24,6,2,...,0.10,0.14,0.18,0.10,0.20,-0.20,0.08,0.12,medium,1
2,cand_00211202,qry_0026400,2024-06-10,sel_00000,west,apparel,growth,24,6,2,...,0.22,0.12,0.12,0.18,0.45,0.04,0.02,0.16,high,0
3,cand_00211203,qry_0026400,2024-06-10,sel_00000,west,apparel,growth,24,6,2,...,0.15,0.16,0.34,0.12,0.16,0.05,0.04,0.10,medium,0
4,cand_00211204,qry_0026400,2024-06-10,sel_00000,west,apparel,growth,24,6,2,...,0.25,0.24,0.42,0.02,0.40,-0.08,0.06,0.36,medium,0

In [3]:
train.promo_tool.value_counts()

promo_tool
coupon_pack                  26400
free_shipping_boost          26400
cashback_offer               26400
bundle_builder               26400
flash_sale_slot              26400
homepage_feature             26400
sponsored_search_boost       26400
loyalty_points_multiplier    26400
Name: count, dtype: int64

In [4]:
train.tool_type.nunique()

6

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211200 entries, 0 to 211199
Data columns (total 45 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   candidate_id               211200 non-null  object
 1   query_id                   211200 non-null  object
 2   snapshot_date              211200 non-null  object
 3   seller_id                  211200 non-null  object
 4   region                     211200 non-null  object
 5   primary_category           211200 non-null  object
 6   seller_tier                211200 non-null  object
 7   week_of_year               211200 non-null  int64
 8   month                      211200 non-null  int64
 9   quarter                    211200 non-null  int64
 10  seller_tenure_days         211200 non-null  int64
 11  orders_30d                 211200 non-null  int64
 12  gmv_30d                    211200 non-null  float64
 13  avg_order_value            211200 non-null  float64
 14  margin_rate                211200 non-null  float64
 15  listing_views_30d          211200 non-null  float64
 16  conversion_rate            211200 non-null  float64
 17  ad_spend_30d               168312 non-null  float64
 18  search_visibility_score    90040 non-null   float64
 19  inventory_fill_rate        211200 non-null  float64
 20  stockout_rate_30d          211200 non-null  float64
 21  repeat_buyer_rate          211200 non-null  float64
 22  seller_rating              211200 non-null  float64
 23  cashback_budget_score      197144 non-null  float64
 24  marketing_readiness_score  211200 non-null  float64
 25  promotion_fatigue_30d      211200 non-null  float64
 26  is_cross_border            211200 non-null  int64
 27  uses_fulfillment_service   211200 non-null  int64
 28  holiday_campaign           211200 non-null  int64
 29  month_end_push             211200 non-null  int64
 30  active_channels            211200 non-null  object
 31  recent_promo_tools         201600 non-null  object
 32  promo_tool                 211200 non-null  object
 33  tool_type                  211200 non-null  object
 34  discount_depth             211200 non-null  float64
 35  visibility_boost           211200 non-null  float64
 36  inventory_synergy          211200 non-null  float64
 37  loyalty_synergy            211200 non-null  float64
 38  margin_penalty             211200 non-null  float64
 39  cross_border_fit           211200 non-null  float64
 40  new_seller_fit             211200 non-null  float64
 41  seasonal_fit               211200 non-null  float64
 42  cost_tier                  211200 non-null  object
 43  is_relevant                211200 non-null  int64
 44  tool_recently_used         211200 non-null  int64
dtypes: float64(22), int64(11), object(12)
memory usage: 72.5+ MB